/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.forms.modificar;

import javax.swing.JOptionPane;
import jframe.classes.Alumne;
import jframe.classes.Grup;
import jframe.classes.LlistaAlumnes;
import jframe.classes.LlistaGrups;
import jframe.classes.LlistaMatricules;
import jframe.classes.LlistaProfessor;
import jframe.classes.Matricula;
import jframe.forms.JFrameMatricula;

/**
 *
 * @author josep
 */
public class JFrameModificarMatricula extends javax.swing.JFrame {

    public static LlistaMatricules ll_m;
    public static LlistaAlumnes ll_a;
    public static LlistaGrups ll_g;
    public static LlistaProfessor ll_p;
    private static int selectedItem = -1;
    private Matricula element;

    /**
     * Creates new form JFrameModificarMatricula
     */
    public JFrameModificarMatricula(LlistaMatricules llista_m, LlistaAlumnes llista_a, LlistaGrups llista_g, LlistaProfessor llista_p, int selectedItem) {
        this.ll_a = llista_a;
        this.ll_m = llista_m;
        this.ll_g = llista_g;
        this.ll_p = llista_p;
        this.setTitle("Administració de Matricules"); //Establim el titul de la finestra
        initComponents();
        this.selectedItem = selectedItem;
        //Mostrar valors als camps del formulari
        element = ll_m.returnList(selectedItem);
        
        nomAlumne.setText(element.getUsuari().getNom());
        nomGrup.setText(element.getGrup().getNomGrup());
        nomInstitut.setText(element.getInstitut());
        if (element.getEstat() == "Actiu") {
            botoAlta.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomGrup = new javax.swing.JTextField();
        botoModificar = new javax.swing.JButton();
        botoRetorn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomInstitut = new javax.swing.JTextField();
        nomAlumne = new javax.swing.JTextField();
        botoAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomGrupActionPerformed(evt);
            }
        });

        botoModificar.setText("Acceptar");
        botoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModificarActionPerformed(evt);
            }
        });

        botoRetorn.setText("Cancelar");
        botoRetorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoRetornActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Modificar Matricules");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Institut:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Alumne:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Grup:");

        nomAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomAlumneActionPerformed(evt);
            }
        });

        botoAlta.setText("Alta");
        botoAlta.setToolTipText("Premer per a donar d'alta i confirmar els canvis de la modificació");
        botoAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoAltaMouseClicked(evt);
            }
        });
        botoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomInstitut, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botoRetorn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomInstitut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(botoAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoModificar)
                    .addComponent(botoRetorn))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomGrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomGrupActionPerformed

    private void botoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModificarActionPerformed
        //Mostrem missatge de confirmació
        int confirm = JOptionPane.showConfirmDialog(this, "Esteu segurs de modificar aquesta matricula?");
        if (confirm == JOptionPane.YES_OPTION) {
            //Cridem al metode per a modificar les dades
            Alumne alumne = ll_a.buscarPerNom(nomAlumne.getText());
            Grup grup = ll_g.buscarPerNom(nomGrup.getText());

            ll_m.modificarMatricula(selectedItem, nomInstitut.getText(), alumne, grup);

            // Tornem a la finestra principal
            JFrameMatricula principalWindow = new JFrameMatricula(ll_m, ll_a, ll_g, ll_p);
            principalWindow.setVisible(true);       //la fem visible
            dispose();                             //eliminem la finestra actual
        }
    }//GEN-LAST:event_botoModificarActionPerformed

    private void botoRetornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoRetornActionPerformed
        /**
         * *************************************
         */
        // Tornem a la finestra principal
        JFrameMatricula principalWindow = new JFrameMatricula(ll_m, ll_a, ll_g, ll_p);
        principalWindow.setVisible(true);       //la fem visible
        dispose();                             //eliminem la finestra actual
    }//GEN-LAST:event_botoRetornActionPerformed

    private void nomAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomAlumneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomAlumneActionPerformed

    private void botoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAltaActionPerformed

    }//GEN-LAST:event_botoAltaActionPerformed

    private void botoAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoAltaMouseClicked
        //Donar d'alta una matricula que esta de baixa
        element.setData_baixa(" ");
        element.setEstat("Actiu");
        Alumne alumne = ll_a.buscarPerNom(nomAlumne.getText());
        Grup grup = ll_g.buscarPerNom(nomGrup.getText());

        ll_m.modificarMatricula(selectedItem, nomInstitut.getText(), alumne, grup);

        // Tornem a la finestra principal
        JFrameMatricula principalWindow = new JFrameMatricula(ll_m, ll_a, ll_g, ll_p);
        principalWindow.setVisible(true);       //la fem visible
        dispose();                             //eliminem la finestra actual
    }//GEN-LAST:event_botoAltaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameModificarMatricula(ll_m, ll_a, ll_g, ll_p, selectedItem).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAlta;
    private javax.swing.JButton botoModificar;
    private javax.swing.JButton botoRetorn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomAlumne;
    private javax.swing.JTextField nomGrup;
    private javax.swing.JTextField nomInstitut;
    // End of variables declaration//GEN-END:variables
}
