/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.forms;

import jframe.forms.modificar.JFrameModificarGrups;
import jframe.forms.alta.JFrameAltaGrups;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import jframe.classes.Grup;
import jframe.classes.LlistaGrups;
import javax.swing.JOptionPane;
import jframe.classes.LlistaAlumnes;
import jframe.classes.LlistaMatricules;
import jframe.classes.LlistaProfessor;

/**
 *
 * @author alumne
 */
public class JFrameGrups extends javax.swing.JFrame {

    public static LlistaMatricules ll_m;
    public static LlistaAlumnes ll_a;
    public static LlistaGrups ll_g;
    public static LlistaProfessor ll_p;
    private int selectedItem = -1;

    /**
     * Creates new form pantalla_principal
     */
    public JFrameGrups(LlistaMatricules llista_m, LlistaAlumnes llista_a, LlistaGrups llista_g, LlistaProfessor llista_p) { //Passar la llista creada al main com a paràmetre al instanciar la classe.
        this.setTitle("Gestió de Grups"); //Definir títol de la finestra.
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel"); //Defineix l'estil de la finestra
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.ll_a = llista_a;
        this.ll_m = llista_m;
        this.ll_g = llista_g;
        this.ll_p = llista_p;
        initComponents();
        grupsTitle.setHorizontalAlignment(JLabel.CENTER); // Fa que el text de grupsTitle estigui centrat al seu contenidor
        emplenar_taula("");
    }

    public void emplenar_taula(String s) {
        Object columnNames[] = {"#", "Nom curt", "Nom", "Familia professional"}; // Array amb el nom de les columnes
        DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Creem un nou model de taula amb l'array que tenim de nom de columnes

        LlistaGrups consulta = ll_g.consulta(s); // Aqui assignem la variable consulta que sigue el que retorne ll_g.consulta, que agafa una string per a filtrar
        // quan s'escriu algo al input de buscar s'actualitza amb el valor que te.
        for (int i = 0; i < consulta.getNumGrupsActuals(); i++) { // Recorrem l'array en el numero de grups que te la consulta
            Grup g = consulta.returnList(i); // Assignem que g serà el grup que està a la posició "i"
            Object rowData[] = {g.getId(), g.getNomCurtGrup(), g.getNomGrup(), g.getFamiliaProfessional()}; // Fem una array que serà la fila en tota l'informació del grup que tenim que mostrar
            model.addRow(rowData); // Afegim la fila al model de taula
        }
        taulaGrups.setModel(model); // Una vegada s'ha completat el bucle, assignem el model que tenim a la taula
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taulaGrups = new javax.swing.JTable();
        afegirGrup = new javax.swing.JButton();
        searchGroups = new javax.swing.JTextField();
        modificarGrup = new javax.swing.JButton();
        borrarGrup = new javax.swing.JButton();
        back = new javax.swing.JButton();
        botoImportar = new javax.swing.JButton();
        botoExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        grupsTitle.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        grupsTitle.setText("Grups");
        grupsTitle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                grupsTitleComponentHidden(evt);
            }
        });

        taulaGrups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        taulaGrups.getTableHeader().setReorderingAllowed(false);
        taulaGrups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaGrupsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taulaGrups);

        afegirGrup.setText("Alta");
        afegirGrup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afegirGrupMouseClicked(evt);
            }
        });
        afegirGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirGrupActionPerformed(evt);
            }
        });

        searchGroups.setText("Search...");
        searchGroups.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchGroupsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchGroupsFocusLost(evt);
            }
        });
        searchGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGroupsActionPerformed(evt);
            }
        });
        searchGroups.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchGroupsKeyTyped(evt);
            }
        });

        modificarGrup.setText("Modificar");
        modificarGrup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarGrupMouseClicked(evt);
            }
        });
        modificarGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarGrupActionPerformed(evt);
            }
        });

        borrarGrup.setText("Baixa");
        borrarGrup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarGrupMouseClicked(evt);
            }
        });
        borrarGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarGrupActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        back.setText("Menu Principal");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        botoImportar.setText("Importar");
        botoImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoImportarActionPerformed(evt);
            }
        });

        botoExportar.setText("Exportar");
        botoExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(afegirGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(grupsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botoImportar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botoExportar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modificarGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrarGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(searchGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(grupsTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botoExportar)
                        .addComponent(botoImportar)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afegirGrup)
                    .addComponent(modificarGrup)
                    .addComponent(borrarGrup))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afegirGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirGrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afegirGrupActionPerformed

    private void searchGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGroupsActionPerformed

    private void grupsTitleComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_grupsTitleComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_grupsTitleComponentHidden

    private void searchGroupsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchGroupsFocusGained
        // TODO add your handling code here:
        if (searchGroups.getText().equals("Search...")) {
            searchGroups.setText("");
        }
    }//GEN-LAST:event_searchGroupsFocusGained

    private void searchGroupsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchGroupsFocusLost
        // TODO add your handling code here:
        if (searchGroups.getText().length() == 0) {
            //searchGroups.setText("Search...");
        }
    }//GEN-LAST:event_searchGroupsFocusLost

    private void afegirGrupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afegirGrupMouseClicked
        JFrameAltaGrups g_a = new JFrameAltaGrups(ll_m, ll_a, ll_g, ll_p); // Al fer click a afegirGrup, instanciem el jframe JFrameAltaGrups
        g_a.setVisible(true); // el fem visible
        dispose(); // i tanquem la finestra que estavem
    }//GEN-LAST:event_afegirGrupMouseClicked

    private void taulaGrupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaGrupsMouseClicked
        selectedItem = (int) taulaGrups.getValueAt(taulaGrups.getSelectedRow(), 0) - 1; // Cada vegada que fem click a algun element de la taula
        //fem que l'atribut selectedItem s'actualitzi per a que sigui l'id de l'element
    }//GEN-LAST:event_taulaGrupsMouseClicked

    private void borrarGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarGrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarGrupActionPerformed

    private void borrarGrupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarGrupMouseClicked
        if (selectedItem != -1) { // selectedItem s'inicialitza amb -1, si no es -1 entra al if
            // Mostrem un missatge de confirmació i fem que conf sigui el que showConfirmDialog retorna
            int conf = JOptionPane.showConfirmDialog(this, "Esteu segurs de borrar aquest grup?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (conf == JOptionPane.YES_OPTION) { // Si hem clickat a Confirmar, entra al if, borra l'element seleccionat, refresca la taula i fica selectedItem a -1 (ningun seleccionat)
                ll_g.borrar(selectedItem);
                emplenar_taula("");
                selectedItem = -1;
            }
        } else { // Si no s'ha seleccionat cap element, mostra un missatge d'error
            JOptionPane.showMessageDialog(this, "Per a realitzar aquesta acció heu de seleccionar un grup de la taula", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_borrarGrupMouseClicked

    private void searchGroupsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchGroupsKeyTyped
        emplenar_taula(searchGroups.getText()); // Cada vegada que s'escriu al input s'actualitza la taula
    }//GEN-LAST:event_searchGroupsKeyTyped

    private void modificarGrupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarGrupMouseClicked
        if (selectedItem != -1) {
            int conf2 = JOptionPane.showConfirmDialog(this, "Esteu segurs de modificar les dades d'aquest grup?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if(conf2 == JOptionPane.YES_OPTION){
               JFrameModificarGrups g_a = new JFrameModificarGrups(ll_m, ll_a, ll_g, ll_p, selectedItem);
                selectedItem = -1;
                g_a.setVisible(true);
                dispose(); 
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Per a realitzar aquesta acció heu de seleccionar un grup de la taula", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modificarGrupMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        //Redireccionem al menu principal
        JFrameMenuPrincipal m = new JFrameMenuPrincipal(ll_m, ll_a, ll_g, ll_p);
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void modificarGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarGrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarGrupActionPerformed

    private void botoImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoImportarActionPerformed
        JFrameCSVImport csv = new JFrameCSVImport(ll_m,ll_a, ll_g, ll_p, 1);
        csv.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoImportarActionPerformed

    private void botoExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoExportarActionPerformed
        JFrameCSVExport csv = new JFrameCSVExport(ll_m,ll_a, ll_g, ll_p, 1);
        csv.setVisible(true);
        dispose();    }//GEN-LAST:event_botoExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGrups(ll_m, ll_a, ll_g, ll_p).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirGrup;
    private javax.swing.JButton back;
    private javax.swing.JButton borrarGrup;
    private javax.swing.JButton botoExportar;
    private javax.swing.JButton botoImportar;
    private javax.swing.JLabel grupsTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarGrup;
    private javax.swing.JTextField searchGroups;
    private javax.swing.JTable taulaGrups;
    // End of variables declaration//GEN-END:variables
}
