/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.forms;

import jframe.forms.modificar.JFrameModificarAlumnes;
import jframe.forms.alta.JFrameAltaAlumnes;
import jframe.classes.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static jframe.forms.JFrameMatricula.ll_m;

/**
 *
 * @author Marc
 */
public class JFrameAlumnes extends javax.swing.JFrame {

    public static LlistaMatricules ll_m;
    public static LlistaAlumnes ll_a;
    public static LlistaGrups ll_g;
    public static LlistaProfessor ll_p;
    private int row = -1;

    //Metode per a emplenar la taula
    public void emplenarTaula(String s) {
        String buscar = s;
        String[][] array = new String[ll_a.comptadorAlumnes][8];
        if (buscar.equals("")) {
            for (int i = 0; i < ll_a.comptadorAlumnes; i++) {
                String id = Integer.toString(ll_a.llistaAlumnes[i].getId());
                array[i][0] = id;
                array[i][1] = ll_a.llistaAlumnes[i].getNom();
                array[i][2] = ll_a.llistaAlumnes[i].getCognom();
                array[i][3] = ll_a.llistaAlumnes[i].getEmail();
                array[i][4] = ll_a.llistaAlumnes[i].getDni();
                array[i][5] = ll_a.llistaAlumnes[i].getData_naixement();
                array[i][6] = ll_a.llistaAlumnes[i].getEscola();
                array[i][7] = ll_a.llistaAlumnes[i].getEstat();
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    array,
                    new String[]{"ID", "Nom", "Cognom", "Email", "DNI", "Data naixement", "Centre", "Estat"}
            ));
            jScrollPane2.setViewportView(jTable1);
        } else {
            int comptador = 0;
            for (int i = 0; i < ll_a.comptadorAlumnes; i++) {
                if ((ll_a.llistaAlumnes[i].toString().toUpperCase()).contains(buscar.toUpperCase())) {
                    String id = Integer.toString(ll_a.llistaAlumnes[i].getId());
                    array[comptador][0] = id;
                    array[comptador][1] = ll_a.llistaAlumnes[i].getNom();
                    array[comptador][2] = ll_a.llistaAlumnes[i].getCognom();
                    array[comptador][3] = ll_a.llistaAlumnes[i].getEmail();
                    array[comptador][4] = ll_a.llistaAlumnes[i].getDni();
                    array[comptador][5] = ll_a.llistaAlumnes[i].getData_naixement();
                    array[comptador][6] = ll_a.llistaAlumnes[i].getEscola();
                    array[comptador][7] = ll_a.llistaAlumnes[i].getEstat();
                    comptador++;
                }
            }

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    array,
                    new String[]{"ID", "Nom", "Cognom", "Email", "DNI", "Data naixement", "Centre", "Estat"}
            ));
            jScrollPane2.setViewportView(jTable1);
        }
    }

    /**
     * Creates new form FinestraLlistar
     */
    public JFrameAlumnes() {
        initComponents();
    }

    public JFrameAlumnes(LlistaMatricules llista_m, LlistaAlumnes llista_a, LlistaGrups llista_g, LlistaProfessor llista_p) {
        this.ll_a = llista_a;
        this.ll_m = llista_m;
        this.ll_g = llista_g;
        this.ll_p = llista_p;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afegir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        buscador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botoExportar = new javax.swing.JButton();
        botoImportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        afegir.setText("Alta");
        afegir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afegirMouseClicked(evt);
            }
        });
        afegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirActionPerformed(evt);
            }
        });

        //LlistaAlumnes.iniciarAlumnes();

        String [][] array = new String [ll_a.comptadorAlumnes][8];

        for (int i = 0; i < ll_a.comptadorAlumnes; i++) {
            String id = Integer.toString(ll_a.llistaAlumnes[i].getId());
            array [i][0] = id;
            array [i][1] = ll_a.llistaAlumnes[i].getNom();
            array [i][2] = ll_a.llistaAlumnes[i].getCognom();
            array [i][3] = ll_a.llistaAlumnes[i].getEmail();
            array [i][4] = ll_a.llistaAlumnes[i].getDni();
            array [i][5] = ll_a.llistaAlumnes[i].getData_naixement();
            array [i][6] = ll_a.llistaAlumnes[i].getEscola();
            array [i][7] = ll_a.llistaAlumnes[i].getEstat();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            array,
            new String [] {
                "ID","Nom", "Cognom", "Email", "DNI", "Data naixement", "Centre", "Estat"
            }
        )
    );
    jScrollPane2.setViewportView(jTable1);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
    jLabel1.setText("Gestió d'alumnes");

    modificar.setText("Modificar");
    modificar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            modificarActionPerformed(evt);
        }
    });

    eliminar.setText("Baixa");
    eliminar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            eliminarActionPerformed(evt);
        }
    });

    buscador.setToolTipText("");
    buscador.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buscadorActionPerformed(evt);
        }
    });
    buscador.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            buscadorKeyTyped(evt);
        }
        public void keyPressed(java.awt.event.KeyEvent evt) {
            buscadorKeyPressed(evt);
        }
    });

    jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    jButton1.setText("Menu Principal");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    botoExportar.setText("Exportar");
    botoExportar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botoExportarActionPerformed(evt);
        }
    });

    botoImportar.setText("Importar");
    botoImportar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botoImportarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(afegir, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(87, 87, 87)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buscador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(botoImportar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botoExportar)))))
            .addGap(58, 58, 58))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(316, 316, 316))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jButton1)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel1))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botoExportar)
                        .addComponent(botoImportar))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(afegir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(37, 37, 37)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Redirigeix a la finestra per a crear un alumne */

    private void afegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirActionPerformed
        this.setVisible(false);
        JFrameAltaAlumnes fc = new JFrameAltaAlumnes(ll_m, ll_a, ll_g, ll_p);
        fc.setTitle("Afegir alumne");
        fc.setVisible(true);
        fc.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_afegirActionPerformed

    private void afegirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afegirMouseClicked

    }//GEN-LAST:event_afegirMouseClicked

    /* Redirigeix a la finestra per a modificar un alumne passant-li les dades de la taula.
    Si no s'ha seleccionat cap alumne, mostrarà un error */

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Has de seleccionar un alumne.");
        } else {
            String idString = jTable1.getModel().getValueAt(row, 0).toString();
            int id = Integer.parseInt(idString);
            String nom = jTable1.getModel().getValueAt(row, 1).toString();
            String cognom = jTable1.getModel().getValueAt(row, 2).toString();
            String email = jTable1.getModel().getValueAt(row, 3).toString();
            String dni = jTable1.getModel().getValueAt(row, 4).toString();
            String data = jTable1.getModel().getValueAt(row, 5).toString();
            String centre = jTable1.getModel().getValueAt(row, 6).toString();
            String estat = jTable1.getModel().getValueAt(row, 7).toString();

            JFrameModificarAlumnes fm = new JFrameModificarAlumnes(ll_m, ll_a, ll_g, ll_p, id, nom, cognom, email, dni, data, centre, estat);
            fm.carregarDades();
            fm.setTitle("Modificar alumne");
            fm.setVisible(true);
            fm.setLocationRelativeTo(null);
            dispose();
            row = -1;
        }

    }//GEN-LAST:event_modificarActionPerformed

    /* Redirigeix a la finestra per a donar de baixa un alumne passant-li les dades de la taula.
    Si no s'ha seleccionat cap alumne, mostrarà un error */

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        row = jTable1.getSelectedRow();

        if (row != -1) {//Comprovem que s'hagi seleccionat una matricula
            //Mostrem missatge de confirmació
            int confirm = JOptionPane.showConfirmDialog(this, "Esteu segurs de donar de baixa aquest alumne?");
            if (confirm == JOptionPane.YES_OPTION) {
                ll_a.eliminarAlumne(row);
                emplenarTaula("");
                row = -1;

            }

        } else {
            //Mostrem error si no selecciona res
            JOptionPane.showMessageDialog(this, "Perfavor selecciona un usuari de la taula", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed

    }//GEN-LAST:event_buscadorActionPerformed

    /* Agafa el text que hi ha al buscador i mostra els resultats que coincideixen */

    private void buscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyTyped
        emplenarTaula(buscador.getText());
    }//GEN-LAST:event_buscadorKeyTyped

    private void buscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyPressed

    }//GEN-LAST:event_buscadorKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Redireccionem al menu principal
        JFrameMenuPrincipal m = new JFrameMenuPrincipal(ll_m, ll_a, ll_g, ll_p);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botoImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoImportarActionPerformed
        JFrameCSVImport csv = new JFrameCSVImport(ll_m,ll_a, ll_g, ll_p, 3);
        csv.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoImportarActionPerformed

    private void botoExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoExportarActionPerformed
        JFrameCSVExport csv = new JFrameCSVExport(ll_m,ll_a, ll_g, ll_p, 3);
        csv.setVisible(true);
        dispose();
    }//GEN-LAST:event_botoExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlumnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlumnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlumnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlumnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameAlumnes fll = new JFrameAlumnes();
                fll.setVisible(true);
                fll.setLocationRelativeTo(null);
            }
        });
    }

    private DefaultTableModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegir;
    private javax.swing.JButton botoExportar;
    private javax.swing.JButton botoImportar;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
