/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.forms.alta;

import jframe.classes.Alumne;
import jframe.classes.Grup;
import jframe.classes.LlistaAlumnes;
import jframe.classes.LlistaGrups;
import jframe.classes.LlistaMatricules;
import jframe.classes.LlistaProfessor;
import jframe.classes.Matricula;
import jframe.forms.select.JFrameAlumneSeleccionar;
import jframe.forms.JFrameMatricula;
import jframe.forms.select.JFrameGrupsSeleccionar;

/**
 *
 * @author josep
 */
public class JFrameAltaMatricula extends javax.swing.JFrame {

    public static LlistaMatricules ll_m;
    public static LlistaAlumnes ll_a;
    public static LlistaGrups ll_g;
    public static LlistaProfessor ll_p;
    public static int selectedItem = -1;
    public static int selectedItemGrup = -1;
    public static int selectedItemAlumne = -1;
    public static String institut;
    public String a;
    public String g;
    public String i;

    /**
     * Creates new form JFrameAltaMatricula
     *
     * @param ll_m
     */
    public JFrameAltaMatricula(LlistaMatricules llista_m, LlistaAlumnes llista_a, LlistaGrups llista_g, LlistaProfessor llista_p) {
        this.ll_a = llista_a;
        this.ll_m = llista_m;
        this.ll_g = llista_g;
        this.ll_p = llista_p;
        this.setTitle("Administració de Matricules"); //Establim el titul de la finestra
        initComponents();
        //Tooltips
        botoAlta.setToolTipText("Premer per acceptar");
        botoSortir.setToolTipText("Premer per a cancelar");
    }

    public JFrameAltaMatricula(LlistaMatricules llista_m, LlistaAlumnes llista_a, LlistaGrups llista_g, LlistaProfessor llista_p, int selectedItemAlumne, int selectedItemGrup, String institut) {
        this.ll_a = llista_a;
        this.ll_m = llista_m;
        this.ll_g = llista_g;
        this.ll_p = llista_p;
        this.selectedItemGrup = selectedItemGrup;
        this.selectedItemAlumne = selectedItemAlumne;
        this.institut = institut;
        this.setTitle("Administració de Matricules"); //Establim el titul de la finestra
        initComponents();
        //Tooltips
        botoAlta.setToolTipText("Premer per acceptar");
        botoSortir.setToolTipText("Premer per a cancelar");
        nomInstitut.setText(institut);

        if (selectedItemAlumne != -1) {
            //Agafar el valor de l'alumne d'una taula
            Alumne alumne = ll_a.returnList(selectedItemAlumne);
            nomAlumne.setText(alumne.getNom());
            a = alumne.getNom();
        }

        if (selectedItemGrup != -1) {
            //Agafar el valor del grup d'una taula
            Grup grup = ll_g.returnList(selectedItemGrup);
            nomGrup.setText(grup.getNomGrup());
            g = grup.getNomGrup();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        botoSortir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomInstitut = new javax.swing.JTextField();
        nomAlumne = new javax.swing.JTextField();
        nomGrup = new javax.swing.JTextField();
        botoAlta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botoSortir.setText("Cancel·lar");
        botoSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSortirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Alta Matricules");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Institut:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Alumne");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Grup:");

        nomInstitut.setBackground(new java.awt.Color(255, 255, 255));
        nomInstitut.setOpaque(false);
        nomInstitut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomInstitutActionPerformed(evt);
            }
        });

        nomAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomAlumneActionPerformed(evt);
            }
        });

        nomGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomGrupActionPerformed(evt);
            }
        });

        botoAlta.setText("Acceptar");
        botoAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAltaActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomInstitut, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botoSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomInstitut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(botoAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoSortir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boto per a tirar enrere
    private void botoSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSortirActionPerformed
        /**
         * *************************************
         */
        // Tornem a la finestra principal
        JFrameMatricula principalWindow = new JFrameMatricula(ll_m, ll_a, ll_g, ll_p);
        principalWindow.setVisible(true);       //la fem visible
        dispose();                             //eliminem la finestra actual
        /****************************************/    }//GEN-LAST:event_botoSortirActionPerformed

    private void nomAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomAlumneActionPerformed
        nomAlumne.setText(a);
    }//GEN-LAST:event_nomAlumneActionPerformed

    private void nomGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomGrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomGrupActionPerformed

    private void botoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAltaActionPerformed
        //Cridem al metode per a inserir matricules

        Alumne alumne = ll_a.buscarPerNom(nomAlumne.getText());
        Grup grup = ll_g.buscarPerNom(nomGrup.getText());

        ll_m.inserirMatricula(nomInstitut.getText(), alumne, grup);

        // Tornem a la finestra principal
        JFrameMatricula principalWindow = new JFrameMatricula(ll_m, ll_a, ll_g, ll_p);
        principalWindow.setVisible(true);       //la fem visible
        dispose();                             //eliminem la finestra actual
    }//GEN-LAST:event_botoAltaActionPerformed

    private void nomInstitutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomInstitutActionPerformed
        nomInstitut.setText(i);
    }//GEN-LAST:event_nomInstitutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tornem a la finestra principal
        JFrameAlumneSeleccionar ju = new JFrameAlumneSeleccionar(ll_m, ll_a, ll_g, ll_p, selectedItemGrup, nomInstitut.getText());
        ju.setVisible(true);       //la fem visible
        dispose(); //eliminem la finestra actual
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Tornem a la finestra principal
        JFrameGrupsSeleccionar jg = new JFrameGrupsSeleccionar(ll_m, ll_a, ll_g, ll_p, selectedItemAlumne, nomInstitut.getText());
        jg.setVisible(true);       //la fem visible
        dispose(); //eliminem la finestra actual
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameAltaMatricula(ll_m, ll_a, ll_g, ll_p).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAlta;
    private javax.swing.JButton botoSortir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomAlumne;
    private javax.swing.JTextField nomGrup;
    private javax.swing.JTextField nomInstitut;
    // End of variables declaration//GEN-END:variables
}
